### ISSUE TITLE
path_max

### ISSUE THREAD

**Issue by liara** [nowsecure/fsmon#14]
The new release fails to build for me on Arch, 4.5.1-1 kernel.  It fails on 

`
util.c:106:19: error: ‘PATH_MAX’ undeclared (first use in this function)
  static char path[PATH_MAX] = {0};
                   ^
`

If I set it to 1024, like it was before, It builds just fine, tho mine is supposed to be 4096. Should I declare my path_max somewhere?

**Comment by radare** [comment]
Already fixed in master
