### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nowsecure/fsmon#15]
I would like to point out that identifiers like "[`_FSMON_H_`](https://github.com/nowsecure/fsmon/blob/bdc59dbdb42776ec0c45c3eb8b12111b2f0edce6/fsmon.h#L1)" and "[`_INCLUDE_UTIL_H_`](https://github.com/nowsecure/fsmon/blob/903b59d060e5a8c6f18000914aa245b2a8b017cb/util.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Are there [a few update candidates left over](https://github.com/nowsecure/fsmon/blob/98e718bf7963ad9149f610287b7dfe595113e4be/fsev.h#L1 "Update candidate")?

**Comment by trufae** [comment]
Fixed in 570a70ef4a522ccec832c6272e8c9a6f598306c8

**Comment by elfring** [comment]
Thanks for [another improvement of affected include guards](https://github.com/nowsecure/fsmon/commit/570a70ef4a522ccec832c6272e8c9a6f598306c8 "Renaming of a few include guards")
