### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [nowsecure/fsmon#16]
[The function "printf"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Formatted output") does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
How do you think about to delete its call from your function "[control_c](https://github.com/nowsecure/fsmon/blob/6a26e3955d7e68bb3a67ea85a20c4044f9cf785e/main.c#L132 "Check signal handling implementation.")"?

**Comment by trufae** [comment]
Should be fixed now in master, thanks for reporting!

**Comment by elfring** [comment]
Which commit should have fixed this issue?

**Comment by elfring** [comment]
Are there [more implementation details to reconsider](https://github.com/nowsecure/fsmon/commit/54919306cdd539266c664bd9cdd355182dc99ba9#diff-2045016cb90d1e65d71c2407a2570927L132 "Update candidate")?
