### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [nowsecure/fsmon#17]
Would you like to add more error handling for return values from functions like the following?
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [hexdump](https://github.com/nowsecure/fsmon/blob/34db9848419a9bbee92337b7561c2338cf4aef6c/util.c#L21)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html) ⇒ [main](https://github.com/nowsecure/fsmon/blob/6a26e3955d7e68bb3a67ea85a20c4044f9cf785e/main.c#L149)

**Comment by trufae** [comment]
sure, will do before 1.2 release

**Comment by trufae** [comment]
i'm not using `signal` anymore. sigaction works better. no return value checks yet. will update the code later

**Comment by trufae** [comment]
checked return values for `alarm` and `sigaction`

**Comment by trufae** [comment]
handling return values for all printf/fprintf calls will mess too much the code and i think the benefits for this are low, so i'm moving this issue to 1.3 for now.

**Comment by trufae** [comment]
See f8e666d4b272876202e21f41252e2e198283db98

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by trufae** [comment]
let's close this for now, we'll see if there's any other missing return  value that is not checked properly

**Comment by elfring** [comment]
There were [update candidates left over](https://github.com/nowsecure/fsmon/blob/663a84a49eb65f15d6e056c93a5adea508af261b/main.c#L86 "Update candidate: callback()").
