### ISSUE TITLE
Android problem

### ISSUE THREAD

**Issue by mcanonic** [nowsecure/fsmon#34]
Hi,
I was trying to compile the code in my linux machine in order to check FS of my android emulator. So I run make and this is what I've got some problem:
mex@hope fsmon]$ make android NDK_ARCH=x86 ANDROID_API=25
for a in x86 ; do \
	make aagt21compile ANDROID_API=25 NDK_ARCH=$a ; \
done
make[1]: Entering directory '/home/mex/prj/simAndroidUser/fsmon'
./ndk-gcc 25 -DHAVE_FANOTIFY=1 -DHAVE_SYS_FANOTIFY=0 -I. -Wall  -o fsmon-and25-x86 main.c util.c backend/*.c
Using /home/mex/Downloads/android-ndk-r10e as NDK path.
Invalid path in NDK environment, please change me.
make[1]: *** [Makefile:141: aagt21compile] Error 1
make[1]: Leaving directory '/home/mex/prj/simAndroidUser/fsmon'
make: *** [Makefile:136: android] Error 2

How can I fix it, please?
M

**Comment by trufae** [comment]
it should be fixed now
