### ISSUE TITLE
the fsmon work in android problem

### ISSUE THREAD

**Issue by 500646** [nowsecure/fsmon#36]
both in arm or x86, the android version seems like not work.it just output this info:
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0
?[33mFSE_CONTENT_MODIFIED?[0m   0       "?[35m?[0m"     0

the make command i use:
make android NDK_ARCH=x86 ANDROID_API=21
make android NDK_ARCH=arm ANDROID_API=21

**Comment by trufae** [comment]
This seems like a regression. Which version if androird are you using to test this?

How do you run fsmon to get those messages?

Also, it is recommended to quote the code snippets to ease reading the issue

Thanks

**Comment by 500646** [comment]
thank you for reply.
I test the x86 binary in Android x86 emulator with 5.0.and anthor arm version in my nexus6 with Android 6.0. 
also I test the x86 binary on releases page with x86 emulator 5.0,it also work incorrect:
![image](https://user-images.githubusercontent.com/10594524/50333967-d10fd680-0541-11e9-9422-d6ac74235097.png)

![image](https://user-images.githubusercontent.com/10594524/50333692-1da6e200-0541-11e9-8c5c-0c878dcc6604.png)
the output is very fast.
same as the x86 binary,the arm binary seems better.

`[0m    0       "[35m[0m"     a5c7e6bd3a927b2381f499b6d023d5c0
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     9d395de55f20c019474850bbc6e6a26d
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     bce517786769d658a491e8d96b29715c
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     9f576b0c6495d48b5d65543dd02bae6d
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     2bcc1256a81824536b3f96039d9e29dc
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     e36bfca89577b5d078e1ac7ac55f31ed
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     572161c85b1ef6230039c668951cfcd8
[0m    0       "[35m[0m"     .
[0m    0       "[35m[0m"     .
[32mFSE_OPEN[0m       0       "[35m[0m"     online
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     online
[0m    0       "[35m[0m"     online
[32mFSE_OPEN[0m       0       "[35m[0m"     present
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     present
[0m    0       "[35m[0m"     present
[32mFSE_OPEN[0m       0       "[35m[0m"     online
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     online
[0m    0       "[35m[0m"     online
[32mFSE_OPEN[0m       0       "[35m[0m"     create
[33mFSE_CONTENT_MODIFIED[0m   0       "[35m[0m"     create
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     create
[0m    0       "[35m[0m"     create
[32mFSE_OPEN[0m       0       "[35m[0m"     qseecomd
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     qseecomd
[32mFSE_OPEN[0m       0       "[35m[0m"     linker
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     linker
[32mFSE_OPEN[0m       0       "[35m[0m"     libc.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libc.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libcutils.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libcutils.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libutils.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libutils.so
[32mFSE_OPEN[0m       0       "[35m[0m"     liblog.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     liblog.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libQSEEComAPI.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libQSEEComAPI.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libdrmfs.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libdrmfs.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libc++.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libc++.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libm.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libm.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libbacktrace.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libbacktrace.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libstdc++.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libstdc++.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libdiag.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libdiag.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libbase.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libbase.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libunwind.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libunwind.so
[32mFSE_OPEN[0m       0       "[35m[0m"     libnetd_client.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     libnetd_client.so
[32mFSE_OPEN[0m       0       "[35m[0m"     librpmb.so
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     librpmb.so
[32mFSE_OPEN[0m       0       "[35m[0m"     raw_rpmb_size_mult
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     raw_rpmb_size_mult
[0m    0       "[35m[0m"     raw_rpmb_size_mult
[32mFSE_OPEN[0m       0       "[35m[0m"     rel_sectors
[33mFSE_STAT_CHANGED[0m       0       "[35m[0m"     rel_sectors
[0m    0       "[35m[0m"     rel_sectors
[0m    0       "[35m[0m"     librpmb.so`

at least I can see some file name.
finally I try to build an arm binary with android 6.0(NDK 27),but seems like the new NDK 27 Directory Structure is different to old version,so it make faild with error.

**Comment by trufae** [comment]
ive added the -n flag to  not spit out ansi escape codes. that wont solve the issue, but  at least will make the output readable on windows consoles

**Comment by trufae** [comment]
You may specify the root directory and use the -n flag (from last release) that may work fine for you. please confirm and i'll close the issue

**Comment by 500646** [comment]
sorry for late reply.
I test the last release fsmon-and-x86 on emulator(android 5.0 x86).it dosen't work.
![image](https://user-images.githubusercontent.com/10594524/52899045-6963c800-3220-11e9-938f-398eadbf178d.png)
and last release fsmon-and-arm in android 6.0 
![image](https://user-images.githubusercontent.com/10594524/52899059-9617df80-3220-11e9-984d-577f807b0f50.png)
I don't understand "You may specify the root directory"?

**Comment by trufae** [comment]
Uhm ive tested it on 6,7,8,9 and works as expected if running as root and passing root means to execute it like this: “fsmon /“

**Comment by trufae** [comment]
To solve the support fort android5 you may need to build fsmon with an older NDK, this "register_atfork" symbol is not coming from fsmon, probably a bionic version change
