### ISSUE TITLE
fsmon binary for android

### ISSUE THREAD

**Issue by ranshalit** [nowsecure/fsmon#37]
Hello,

Does the make for android should be done in android environemnt ?
Can you please provide the binary or apk for this application ?

Thanks!

**Comment by trufae** [comment]
Builds are in the releases page. This is built with the ndk, but can be compiled from termux too

**Comment by ranshalit** [comment]
Thank you very much!

**Comment by chocologurt** [comment]
Hi @ranshalit , may i ask how do you install fsmon into your android phone? I have been trying for the past few days but I'm not sure if i'm doing correctly.
