### ISSUE TITLE
Investigate adding container-required to entitlements.plist to improve support for checkra1n on iOS

### ISSUE THREAD

**Issue by alanjhenderson** [nowsecure/fsmon#46]
fsmon-ios is not able to run from /var/tmp on iOS devices jailbroken with checkra1n. The binary is able to run with the following additional entitlement:

```
<key>com.apple.private.security.container-required</key>
<false/>
```

Tested on iPhone X running iOS 13.7 and iPhone SE (1st Gen) running iOS 14.1. I've not been able to test on lower iOS versions with other jailbreaks.

**Comment by trufae** [comment]
Thank you! I can confirm
