### ISSUE TITLE
'make install' fails on OS X

### ISSUE THREAD

**Issue by ianbannerman** [nowsecure/fsmon#5]
Commit 6e64950486b81a351b39d01d861be74e0a35380 changed OS X compilation to no longer generate a binary named `fsmon-fat`, rather just `fsmon`. The `make install` command is still looking for  `fsmon-fat` though and will error:

<img width="585" alt="make_make_install" src="https://cloud.githubusercontent.com/assets/6620025/13199097/3fee8ac4-d7e1-11e5-9f90-c8efba1dfc10.png">

Updating `Makefile` to remove `-fat` from the install command resolves this:

<img width="593" alt="make_install_edit" src="https://cloud.githubusercontent.com/assets/6620025/13199114/c4bab412-d7e1-11e5-8598-64e35056086e.png">

Thank you for an absolutely **fantastic** tool! Absolutely love fsmon :+1:

**Comment by trufae** [comment]
Thanks for reporting! I renamed that file in the last moment and forgot to check the `install` target.

Glad to hear that it's useful for you too! :)
