### ISSUE TITLE
build for Android on macOS failed

### ISSUE THREAD

**Issue by leleliu008** [nowsecure/fsmon#53]
https://github.com/nowsecure/fsmon/archive/1.8.4.tar.gz

I suggest you using following code to test if is Android target:

```make
TARGET_MACHINE := $(shell $(CC) -dumpmachine 2>/dev/null)

ifneq ($(findstring -android,$(TARGET_MACHINE)),)
```

**Comment by trufae** [comment]
Can you submit a pr instead? Its easier to review in there and you get credit for the patch. Just click in the pencil icon no need to use the shell and fork the repo

**Comment by leleliu008** [comment]
ok, I will try it later.
