### ISSUE TITLE
./fsmon-ios: line 2: syntax error: unexpected word (expecting ")")

### ISSUE THREAD

**Issue by pwnedDesal** [nowsecure/fsmon#56]
![image](https://github.com/nowsecure/fsmon/assets/6646675/208bbe92-7e5d-4713-935b-f32ec791681a)

**Comment by trufae** [comment]
The last build is quite old. you can compile it yourself, but i'm adding CI jobs to make all that stuff in the CI and cut a new release

**Comment by trufae** [comment]
Should be fixed in https://github.com/nowsecure/fsmon/releases/tag/1.8.6
