### ISSUE TITLE
fanotify_mark: Bad file descriptor

### ISSUE THREAD

**Issue by itJunky** [nowsecure/fsmon#9]
```
> sudo fsmon
fanotify_mark: Bad file descriptor
```

Whats wrong? How can i use it?

**Comment by trufae** [comment]
Is this issue on android? can you try if the last commit fixes the issue? i've uploaded a build in https://github.com/nowsecure/fsmon/releases/tag/1.0 under the name `fsmon-kitkat`

**Comment by liara** [comment]
Same here on archlinux. 

```
> sudo fsmon
fanotify_mark: Bad file descriptor
```

**Comment by trufae** [comment]
should be fixed now in master.

thanks

**Comment by liara** [comment]
It works now. Thank you. Here is your package, mister: [https://aur.archlinux.org/packages/fsmon-git](https://aur.archlinux.org/packages/fsmon-git)

Nice utility.

**Comment by trufae** [comment]
Awesome! Thanks
